language: python
python:
  - "3.5"
  - "3.6"
  - "3.7-dev"

sudo: required

cache: pip

install:
  - cd Python; python setup.py install

script:
  - pip install -U .[test,doc]
  - python setup.py test
  - cd doc; make html; cd ..

deploy:
  provider: pypi
  user: scottgigante
  password: ${PYPI_PASSWORD}
  distributions: sdist bdist_wheel
  skip_existing: true
  skip_cleanup: true
  on:
    tags: true
    branch: master